import React, { useEffect, useState } from "react";
import { openai, supabase } from "./config.js";
import podcasts from "./content.js";

export default function CreateAnEmbedding() {
  const [embedding, setEmbedding] = useState(null);

  const query = "Jammin' in the Big Easy";

  /*
  Create an embedding from the user input and return a 
  semantically matching text chunk from the database 
*/

  // Create a vector embedding representing the input text
  const createEmbedding = async  (inputquery) => {
    const embeddingResponse = await openai.embeddings.create({
      model: "text-embedding-ada-002",
      input: inputquery,
    });

    // The vector generated by OpenAI
    const embedding = embeddingResponse.data[0].embedding;    

    // Query Supabase for nearest vector match
    const { data } = await supabase.rpc("match_documents", {
      query_embedding: embedding,
      match_threshold: 0.5,
      match_count: 2,
    });

    console.log(data); //contains id, similarity, lenth, content
    console.log(data[0].content, data[0].similarity);
    
        
    

    return {
        data, embedding 
    };
  };



  const storeToDB = async () => {
    // Insert content and embedding into Supabase
    await supabase.from("documents").insert(embedding);
    console.log("Storing complete!");
  };

  useEffect(() => {
    const fetchData = async () => {
      const data = await createEmbedding(query);      
      setEmbedding(data);
      console.log("Embedding complete!");
      console.log('data', data)
    };

    fetchData();
  }, []);

  return (
    <div>
      <button
        className=" bg-slate-300 border-2 border-gray-600 m-2 "
        onClick={storeToDB}
      >
        Store to DB
      </button>
      <h1>Embedding</h1>
      <p>Embedding: {embedding ? JSON.stringify(embedding) : "Loading..."}</p>
    </div>
  );
}
